name: Release Build and Upload

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Get repository name without owner
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

    - name: Zip dist directory
      run: zip -r "${{ env.REPOSITORY_NAME }}_v${{ github.ref_name }}.zip" dist/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "./${{ env.REPOSITORY_NAME }}_v${{ github.ref_name }}.zip"
        asset_name: "${{ env.REPOSITORY_NAME }}_v${{ github.ref_name }}.zip"
        asset_content_type: application/zip
